export const TX_ERRORS = Object.freeze({
  tx_failed: 'Transaction failed',
  tx_too_early: 'Too early',
  tx_too_late: 'Too late',
  tx_missing_operation: 'Missing Operation',
  tx_bad_auth: 'Bad auth',
  tx_no_account: 'No source account',
  tx_bad_auth_extra: 'Bad auth extra',
  tx_internal_error: 'Internal error',
  tx_account_blocked: 'Account blocked',
  tx_duplication: 'Transaction duplication',
  tx_insufficient_fee: 'The total fee amount is greater than the max fee amount specified by tx source',
  tx_source_underfunded: 'Not enough funds for tx fee',
  tx_commission_line_full: 'Charging tx fee would cause uint64 overflow',
  tx_fee_incorrect_precision: 'Cannot charge the fee for the transaction. The fee is charged with a non-divisible asset, and the total calculated amount of the fee would cause this asset to split',
  tx_no_role_permission: 'Source account does not have rule which allows him send transaction, or such rule forbid to do this',
  op_inner: 'Op inner',
  op_bad_auth: 'You don’t have permission to complete this action',
  op_no_account: 'Target account does not exist',
  op_no_entry: 'There is no entry which is tried to get by specified id in operation',
  op_not_supported: 'Such operation currently is not supported',
  op_account_blocked: 'Operations from blocked account are not allowed',
  op_no_counterparty: 'No counterparty',
  op_counterparty_blocked: 'Counterparty account is blocked',
  op_counterparty_wrong_type: 'Counterparty has wrong account type',
  op_bad_auth_extra: 'Bad auth extra',
  op_account_type_mismatched: 'Wrong account type in operation. Refresh page and try again',
  op_invalid_destination: 'Source id matches with destination account id',
  op_rule_is_used: 'Not allowed to remove rule which is used',
  op_no_such_rule: 'There is no rule with such id',
  op_default_rule_id_duplication: 'Not allowed to set default rule id, they will be set automatically',
  op_invalid_weight: 'Weight must not be bigger than 1000',
  op_invalid_signer_data: 'Error returned from signer creation',
  op_no_signer_data: 'There must be at least one signer for new account',
  op_role_is_used: 'Not allowed to remove role which is used',
  op_rule_id_duplication: 'Not allowed to set equal rule ids',
  op_invalid_fee_type: 'Invalid fee type',
  op_malformed_range: 'Invalid range',
  op_range_overlap: 'Range you entered overlapped with another one. Delete or reduce an old one before creating new',
  op_sub_type_not_exist: 'Subtype not exist',
  op_not_allowe: 'Not allowed',
  op_no_such_role: 'Creating account with not existing role not allowed',
  op_invalid_signature: 'Signature does not correspond public key, which is allowed to perform such operations',
  op_invalid_pre_issuer: 'New pre issuer public key is the same as existing',
  op_type_mismatch: 'Type mismatch',
  op_invalid_amount: 'Invalid amount',
  op_balance_mismatch: 'Asset of balance and asset of operation are not equal',
  op_reviewer_not_found: 'Reviewer not found',
  op_invalid_details: 'Invalid details',
  op_fee_mismatch: 'Fees mismatched',
  op_destination_not_found: 'Destination not found',
  op_request_not_found: 'Request not found',
  op_asset_already_exists: 'Asset already exists',
  op_invalid_max_issuance_amount: 'Invalid max issuance amount',
  op_invalid_code: 'Invalid asset code',
  op_invalid_name: 'Invalid asset name',
  op_request_already_exists: 'This request already exists in the system',
  op_stats_asset_already_exists: 'It can be only one stats asset in the system',
  op_line_full: 'Payment would cause a destination account to exceed their declared trust limit for the asset being sent',
  op_fee_mismatched: 'Fees mismatched',
  op_balance_account_mismatched: 'Account id has no such balance',
  op_balance_assets_mismatched: 'Asset of balance and asset of operation are not equal',
  op_src_balance_not_found: 'Source balance not found',
  op_reference_duplication: 'You cannot make two issuances with the same reference',
  op_stats_overflow: 'Overflow during statistics calculation',
  op_limits_exceeded: 'The operation exceeds limits set to your account. Check "Limits" page for your current limits.',
  op_not_allowed_by_asset_policy: 'This action is not allowed by asset policy',
  op_already_exists: 'Entry already exists',
  op_invalid_asset: 'Invalid asset',
  op_invalid_action: 'Invalid action',
  op_invalid_policies: 'Invalid policies',
  op_asset_not_found: 'Asset not found',
  op_pair_not_traded: 'Asset not tradable',
  op_underfunded: 'Not enough funds. Reduce the amount and try again',
  op_cross_self: 'Current order crosses your existing order',
  op_offer_overflow: 'Failed to create offer',
  op_asset_pair_not_tradable: 'Asset is not tradable',
  op_physical_price_restriction: 'Price cannot be lower than physical',
  op_current_price_restriction: 'Price cannot be lower than current',
  op_invalid_percent_fee: 'Invalid percent fee',
  op_insufficient_price: 'Order insufficient price',
  op_success: 'Success',
  op_malformed: 'Operation you are trying to create is malformed in some way',
  op_balance_not_found: 'Balance not found',
  op_invoice_overflow: 'Failed to create invoice',
  op_not_found: 'Not found',
  op_too_many_invoices: 'Too many invoices',
  op_can_not_delete_in_progress: 'Cannot delete request while it is progress',
  op_invalid_external_details: 'External details are invalid',
  op_asset_is_not_withdrawable: 'It is not allowed to withdraw specified asset',
  op_conversion_price_is_not_available: 'Conversion price is not available',
  op_conversion_overflow: 'Overflow during conversion',
  op_converted_amount_mismatched: 'Specified converted amount does not match calculated',
  op_balance_lock_overflow: 'Too much assets are locked in specified balance',
  op_invalid_universal_amount: 'Unexpected universal amount value',
  op_initial_preissued_exceeds_max_issuance: 'Available for issuance amount exceeds max issuance amount',
  op_base_asset_or_asset_request_not_found: 'Asset of asset creation request for base asset not found',
  op_quote_asset_not_found: 'Quote asset does not exists or there is no asset pair with quote asset and default quote asset',
  op_invalid_price: 'Price can not be 0',
  op_invalid_cap: 'Soft cap should not exceed Hard cap',
  op_insufficient_max_issuance: 'Asset’s max issuance amount is insufficient to fulfill soft cap',
  op_invalid_asset_pair: 'One of the assets (base or quote) has invalid code or they are equal',
  op_not_authorized: 'Account not authorized to perform issuance of the asset',
  op_exceeds_max_issuance_amount: 'Maximal issuance amount will be exceeded after issuance',
  op_receiver_full_line: 'Total funds of receiver will exceed UINT64_MAX after issuance',
  op_fee_exceeds_amount: 'Fee is more than amount to issue',
  op_invalid_fee_hash: 'Invalid fee hash was passed, recalculate it',
  op_asset_mismatched: 'Assets mismatched',
  op_price_does_not_match: 'Prices does not match',
  op_insufficient_preissued: 'Insufficient amount of asset available for issuance',
  op_not_verified_cannot_have_policies: 'Not verified account can not have policies',
  op_price_is_invalid: 'Price is invalid in some way',
  op_update_is_not_allowed: 'Update is not allowed',
  op_invalid_reason: 'Reason (CreatorDetails) must be empty if approving and not empty if rejecting',
  op_hash_mismatched: 'Request hash mismatched',
  op_type_mismatched: 'Request type mismatched',
  op_reject_not_allowed: 'Reject not allowed, use permanent reject',
  op_asset_does_not_exists: 'Asset does not exist',
  op_max_issuance_amount_exceeded: 'Max issuance amount exceeded',
  op_insufficient_available_for_issuance_amount: 'Insufficient available for issuance amount',
  op_full_line: "Can't fund balance - total funds exceed system limit",
  op_base_asset_does_not_exists: 'Base asset does not exist',
  op_hard_cap_will_exceed_max_issuance: 'Hard cap will exceed max issuance',
  op_insufficient_preissued_for_hard_cap: 'Insufficient amount of asset available for hard cap',
  op_external_sys_acc_not_allowed: 'Op contains external system account ID which should be generated on core level',
  op_external_sys_id_exists: 'External system account ID already exists',
  op_limits_update_request_reference_duplication: 'Such request already exists',
  op_invalid_pre_confirmation_details: 'Invalid pre confirmation details',
  op_requires_kyc: 'You or your counterparty need to complete KYC to use specified asset',
  op_requestor_is_blocked: 'Requestor is blocked',
  op_version_is_not_supported_yet: 'Version of this operation is not supported yet',
  op_balance_already_exists: 'Balance already exists',
  op_no_available_id: 'No available external system account id for binding',
  op_auto_generated_type_not_allowed: 'Auto generated external system type is not allowed to bind',
  op_acc_to_update_does_not_exist: "Account to change role data doesn't exist",
  op_request_exist: 'Request already exists',
  op_same_acc_type_to_set: 'Account role and are the same',
  op_request_does_not_exist: 'Request does not exist',
  op_permanent_reject_not_allowed: 'Permanent reject not allowed, use reject',
  op_pending_request_update_not_allowed: "User not allowed to update reviewable request if it isn't rejected",
  op_not_allowed_to_update_request: 'Master not allowed to update ChangeRoleRequest',
  op_invalid_change_role_request_data: 'Not allowed to change destination account, role to set or set custom tasks on update request',
  op_invalid_creator_details: 'Invalid json details or details length exceed max length',
  op_non_zero_tasks_to_remove_not_allowed: 'Non-zero value of tasksToRemove field is not allowed in reject reviewable request',
  op_invalid_fee_version: 'Version of fee entry is greater than ledger version',
  op_too_many_rule_ids: 'Count of rule ids exceed max allowed count',
  op_invalid_fee_asset: 'Asset code of fee asset is invalid',
  op_fee_asset_not_allowed: 'Fee asset not allowed',
  op_cross_asset_fee_not_allowed: 'Fee asset on payment fee type can differ from asset iff payment fee subtype is OUTGOING',
  op_fee_asset_not_found: 'Fee asset not found',
  op_asset_pair_not_found: 'Cannot create cross asset fee entry without existing asset pair',
  op_invalid_asset_pair_price: 'Asset pair price is <= 0',
  op_destination_account_not_found: 'Destination account not found',
  op_destination_balance_not_found: 'Destination balance not found',
  op_invalid_destination_fee: 'Destination fee is invalid',
  op_invalid_destination_fee_asset: 'Destination fee asset must be the same as source balance asset',
  op_fee_asset_mismatched: 'Fee asset from operation not the same as fee asset from database',
  op_insufficient_fee_amount: 'Insufficient fee amount',
  op_balance_to_charge_fee_from_not_found: 'Balance to charge fee from not found',
  op_payment_amount_is_less_than_dest_fee: 'Payment amount is less than destination fee',
  op_change_role_tasks_not_found: 'There is no key value with change_role_tasks key',
  op_invalid_type: 'Invalid key value type at for such key',
  op_source_underfunded: 'Source account underfunded',
  op_source_balance_lock_overflow: 'Overflow while locking amount from source balance',
  op_requires_verification: 'You or your counterparty need to be verified to use specified asset',
  op_promotion_update_request_invalid_asset_pair: 'One of the assets (base or quote) has invalid code or they are equal',
  op_promotion_update_request_invalid_price: 'Price can not be 0',
  op_promotion_update_request_invalid_cap: 'Soft cap should not exceed Hard cap',
  op_promotion_update_request_invalid_details: 'CreatorDetails is invalid JSON',
  op_promotion_update_request_already_exists: 'PromotionUpdateRequest already exists',
  op_promotion_update_request_not_found: 'PromotionUpdateRequest not found',
  op_invalid_new_end_time: 'New end time is before start time or current ledger close time',
  op_payment_v1_no_longer_supported: 'Use payment v2 to perform any payment',
  op_not_allowed_to_remove: 'Only request creator can remove request',
  op_contract_not_found: 'There is no opened contract with such id',
  op_only_contractor_can_attach_invoice_to_contract: 'Not allowed to attach invoice to contract',
  op_sender_account_mismatched: 'Not allowed to use not customer account in contract invoice',
  op_invoice_is_approved: 'Not allowed to remove approved invoice request',
  op_amount_mismatched: 'Amount in invoice request and details in review invoice request must be equal',
  op_destination_balance_mismatched: 'Balance from invoice request and details in review invoice request must be equal',
  op_not_allowed_account_destination: 'Not allowed to send to account in review invoice request',
  op_required_source_pay_for_destination: 'Source must pay fee for destination',
  op_source_balance_mismatched: 'Source balance must be equal source balance from response create invoice request',
  op_invoice_receiver_balance_lock_amount_overflow: 'Receiver balance has to much lock amount',
  op_invoice_already_approved: 'Not allowed to approve invoice request second time',
  op_payment_v2_malformed: 'Payment v2 malformed in some way in approve invoice request',
  op_too_many_contracts: 'Reached contract max count for contractor limit',
  op_details_too_long: 'CreatorDetails to long',
  op_too_many_contract_details: 'Reached max contract details count limit',
  op_dispute_reason_too_long: 'Dispute reason to long',
  op_already_confirmed: 'Not allowed to confirm contract second time',
  op_invoice_not_approved: 'Not allowed to confirm contract when all invoices not approved',
  op_dispute_already_started: 'Not allowed start dispute second time',
  op_resolve_dispute_now_allowed: 'Only escrow can resolve dispute',
  op_confirm_not_allowed: 'Only customer and contractor can confirm contract',
  op_customer_balance_overflow: 'Customer balances amounts exceed max amount',
  op_system_tasks_not_allowed: 'Source is trying to set one of the core flags',
  op_issuance_tasks_not_found: "Issuance tasks have not been provided by the source and don't exist in KeyValue table",
  op_cannot_create_for_acc_id_and_acc_type: 'Limits cannot be created for account ID and account type simultaneously',
  op_invalid_limits: 'Invalid limits',
  op_contract_details_too_long: 'Customer details has exceeded max contract details length',
  op_lower_bound_not_exceeded: 'Requested amount to withdraw is too small',
  op_request_id_invalid: 'Request id can not be equal zero',
  op_holders_not_found: 'There is no balances with such asset and total amount more than min',
  op_asset_not_transferable: 'Asset must have transferable policy',
  op_fee_exceeds_actual_amount: 'Fee more than actual amount to be payed',
  op_total_fee_overflow: 'Unexpected state, sum of fixed and calculated fee exceeded max amount',
  op_min_amount_too_big: 'There is no receivers which can receive more than minPayoutAmount',
  op_incorrect_precision: 'The asset we operate on, does not allow such precise amounts',
  op_incorrect_amount_precision: 'The asset we operate on, does not allow such precise amounts',
  op_no_role_permission: "Role permission for operation doesn't exist",
  op_invalid_trailing_digits_count: 'Count of trailing digits must be equal or less than 6',
  op_atomic_swap_bid_overflow: 'Quote amount one of quote asset has exceeded limit',
  op_base_asset_not_found: 'There is no asset with such asset code',
  op_base_asset_cannot_be_swapped: 'Base asset must have CAN_BE_BASE_IN_ATOMIC_SWAP policy',
  op_quote_asset_cannot_be_swapped: 'Quote asset must have CAN_BE_QUOTE_IN_ATOMIC_SWAP policy',
  op_base_balance_not_found: 'There is no balance with such balance id',
  op_assets_are_equal: 'Not allowed to set quote asset equal to base asset',
  op_base_balance_underfunded: "There isn't enough amount on base balance",
  op_invalid_base_amount: 'Not allowed to set zero amount',
  op_invalid_quote_asset: 'Quote asset code is invalid',
  op_bid_not_found: 'There is no atomic swap bid with such bid id',
  op_bid_underfunded: 'Atomic swap bid has not enough available amount',
  op_aswap_bid_not_found: 'There is no atomic swap bid with such bid id',
  op_aswap_bid_underfunded: 'Atomic swap bid has not enough available amount',
  op_aswap_purchaser_full_line: 'Seller balance amount exceed max amount',
  op_aswap_bid_insufficient_fee: 'Fee amount not enough to perform such action',
  op_atomic_swap_tasks_not_found: 'There is no key value for atomic swap tasks',
  op_already_cancelled: 'Atomic swap bid has already canceled',
  op_bid_is_cancelled: 'Cannot create atomic swap request for cancelled bid',
  op_cannot_create_aswap_request_for_own_bid: 'Cannot create atomic swap request for own bid',
  op_invalid_amount_precision: 'The asset we operate on, does not allow such precise amounts',
  op_invalid_preissued_amount_precision: 'Initial pre issued amount does not match precision set by trailing digits count',
  op_invalid_max_issuance_amount_precision: 'Maximum issuance amount does not match precision set by trailing digits count',
  op_withdrawal_tasks_not_found: 'There is no key value for withdrawal tasks',
  op_not_allowed_to_set_withdrawal_tasks: 'Not allowed to set withdrawal tasks',
  op_asset_create_tasks_not_found: 'There is no key value for asset creation tasks',
  op_asset_update_tasks_not_found: 'There is no key value for asset update tasks',
  op_invoice_tasks_not_found: 'There is no key value for invoice tasks',
  op_withdrawal_zero_tasks_not_allowed: 'Withdrawal zero tasks are not allowed',
  op_removing_not_set_tasks: 'Cannot remove tasks which were not set',
  op_invalid_update_details_request_data: 'There are invalid update details in request',
  op_not_allowed_to_set_tasks_on_update: 'Not allowed to set tasks on update',
  op_contract_create_tasks_not_found: 'There is no key value for contract creation tasks',
  op_zero_value_not_allowed: 'Not allowed to use zero in value for such key',
  op_license_violation: 'License has expired. Admin operations are not allowed. Please contact enterprise@distributedlab.com',
  op_auto_review_failed: 'Auto review of created request has failed',
  op_skipped: 'Operation processing has been skipped as previous operation in the same transaction failed',
  op_number_of_admins_exceeds_license: 'Number of admins violates license restriction. Please contact enterprise@distributedlab.com',
  op_account_not_found: 'There is no account with such id',
  op_role_not_found: 'There is no role with such id',
  op_poll_not_ready: 'Cannot close ongoing poll, please wait until it end time is passed.',
  op_not_authorized_to_close_poll: 'Not authorized to close poll, please contact poll owner to resolve the issue.',
  op_create_poll_tasks_not_found: 'Create poll tasks not found, please contact admin to resolve the issue.',
  op_result_provider_not_found: 'Result provider account not found, please check the field and retry.',
  op_invalid_dates: 'Start time cannot be after end time, please check the fields and retry.',
  op_invalid_start_time: 'Start time of the poll is in the past.',
  op_invalid_end_time: 'End time cannot be in the past, please check the field and retry.',
  op_invalid_vote: 'Invalid vote choice, please contact poll system owner to resolve the issue.',
  op_poll_not_found: 'Poll with the provided ID not found, please contact system owner to resolve the issue,',
  op_vote_exists: 'You already voted to this poll, please remove your current vote and retry.',
  op_poll_type_mistmatched: 'Poll type specified in vote is mismatched with the one in poll. Please contact system owner to resolve the issue.',
  op_poll_type_mismatched: 'Poll type specified in vote is mismatched with the one in poll. Please contact system owner to resolve the issue.',
  op_poll_not_started: 'Poll is not started yet, please wait until start time passed and retry.',
  op_poll_ended: 'Poll is ended. We so sorry, but you cannot vote in the poll anymore.',
  op_vote_not_found: 'Cannot remove specified vote, please contact system owner to resolve the issue.',
  op_start_end_invalid: 'Crowdfunding should not end before start',
  op_invalid_end: 'Trying to create crowdfunding which already ended',
  op_request_or_sale_already_exists: 'Crowdfunding creation request or crowdfunding already exists for specified asset',
  op_order_book_does_not_exists: 'Specified crowdfunding does not exists or already closed',
  op_sale_is_not_started_yet: 'Crowdfunding has not been started yet',
  op_sale_already_ended: 'Crowdfunding already ended',
  op_order_violates_hard_cap: 'Offer violates maximal goal restriction of the crowdfunding',
  op_cant_participate_own_sale: 'Can not participate in the own crowdfunding',
  op_sale_is_not_active: 'Crowdfunding is not active',
  op_sale_not_found: 'Crowdfunding not found',
  op_invalid_new_details: 'New crowdfunding details is invalid JSON',
  op_update_details_request_already_exists: 'Update crowdfunding details request already exists',
  op_update_details_request_not_found: 'Update crowdfunding details request to amend not found',
  op_invalid_sale_state: 'Invalid crowdfunding state',
  op_promotion_update_request_start_end_invalid: 'Crowdfunding should not end before start',
  op_invalid_sale_new_end_time: 'New crowdfunding end time is before start time or current ledger close time',
  op_update_end_time_request_already_exists: 'This request already exists',
  op_update_end_time_request_not_found: 'Associated request cannot not found',
  op_sale_create_tasks_not_found: 'There is no key value for crowdfunding creation tasks',
  op_sale_update_details_tasks_not_found: 'There is no key value for crowdfunding details update tasks',
})
