#!/bin/sh

set -ex

RELEASE=$CI_COMMIT_REF_NAME
docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PWD
docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $DH_IMAGE:$RELEASE
docker push $DH_IMAGE:$RELEASE
